#!/usr/bin/env python3  
#coding: utf-8

#基于训练好的词向量模型进行聚类
#聚类采用Kmeans算法
import math
import re
import json
import jieba
import numpy as np
from gensim.models import Word2Vec
from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import euclidean_distances
from collections import defaultdict

#输入模型文件路径
#加载训练好的模型
def load_word2vec_model(path):
    model = Word2Vec.load(path)
    return model

def load_sentence(path):
    sentences = set()
    with open(path, encoding="utf8") as f:
        for line in f:
            sentence = line.strip()
            sentences.add(" ".join(jieba.cut(sentence)))
    print("获取句子数量：", len(sentences))
    return sentences

#将文本向量化
def sentences_to_vectors(sentences, model):
    vectors = []
    for sentence in sentences:
        words = sentence.split()  #sentence是分好词的，空格分开
        vector = np.zeros(model.vector_size)
        #所有词的向量相加求平均，作为句子向量
        for word in words:
            try:
                vector += model.wv[word]
            except KeyError:
                #部分词在训练中未出现，用全0向量代替
                vector += np.zeros(model.vector_size)
        vectors.append(vector / len(words))
    return np.array(vectors)


def main():
    model = load_word2vec_model(r"model.w2v") #加载词向量模型
    sentences = load_sentence("titles.txt")  #加载所有标题
    vectors = sentences_to_vectors(sentences, model)   #将所有标题向量化

    n_clusters = int(math.sqrt(len(sentences)))  #指定聚类数量
    print("指定聚类数量：", n_clusters)
    kmeans = KMeans(n_clusters)  #定义一个kmeans计算类
    kmeans.fit(vectors)          #进行聚类计算

    sentence_distance_dict = defaultdict(list)
    labels = kmeans.labels_
    clusters = [vectors[labels == i] for i in range(n_clusters)] ## 簇分组
    cluster_centers = kmeans.cluster_centers_

    for i in range(n_clusters):
        cluster = clusters[i]
        center = cluster_centers[i]
        if len(cluster) == 0:
            print(f"簇 {i} 没有数据")
            continue
        # 计算簇内所有向量到中心的距离
        distances = euclidean_distances(cluster, center.reshape(1, -1)).flatten()
        avg_dist = np.mean(distances)
        # print(f"簇 {i} 的类内平均距离：{avg_dist:.4f}")
        sentence_distance_dict[i].append(avg_dist)
    sorted_sentence_distance_dict = sorted(sentence_distance_dict.items(), key=lambda d: d[1], reverse=False)
    print("按簇类内平均距离从小到大排列如下：")
    for i in range(len(sorted_sentence_distance_dict)):
        print(f"簇{sorted_sentence_distance_dict[i][0]}的平均距离为: {sorted_sentence_distance_dict[i][1][0]}")
        print("---------------------------------------")

if __name__ == "__main__":
    main()

